# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Typed models for the hospital triage and scheduling benchmark."""

from typing import Literal

from openenv.core.env_server.types import Action, Observation, State
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, model_validator


TaskName = StrictStr
ActionCommand = Literal[
    "BookAppointment",
    "SendToER",
    "RequestMoreInfo",
    "EscalateToClinician",
    "ConfirmRecommendation",
]
PatientAcuity = Literal["routine", "urgent", "critical"]
PatientDisposition = Literal["waiting", "scheduled", "er", "canceled"]
DoctorStatus = Literal["available", "busy", "sick"]
RoomType = Literal["exam", "er", "consult"]
UncertaintyLevel = Literal["low", "medium", "high"]
CapacityPressure = Literal["low", "medium", "high"]
RecommendationStatus = Literal["pending", "confirmed", "dismissed"]
AuditActor = Literal["agent", "clinician", "system"]


class RewardComponent(BaseModel):
    """One deterministic grading component."""

    model_config = ConfigDict(extra="forbid")

    name: StrictStr = Field(..., description="Stable component identifier.")
    score: float = Field(..., ge=0.0, le=1.0, description="Component score contribution.")
    detail: StrictStr = Field(..., description="Human readable explanation.")


class RewardBreakdown(BaseModel):
    """Structured reward payload for graders and debugging."""

    model_config = ConfigDict(extra="forbid")

    score: float = Field(default=0.0, ge=0.0, le=1.0)
    dangerous: StrictBool = Field(default=False)
    message: StrictStr = Field(default="")
    components: list[RewardComponent] = Field(default_factory=list)


class AppointmentDetails(BaseModel):
    """A booked or canceled appointment."""

    model_config = ConfigDict(extra="forbid")

    patient_id: StrictStr
    doctor_id: StrictStr
    doctor_name: StrictStr
    specialty: StrictStr
    room_id: StrictStr
    time_slot: StrictStr
    status: Literal["scheduled", "canceled"] = "scheduled"


class PendingRecommendation(BaseModel):
    """Human-reviewable recommendation generated by the system or clinician."""

    model_config = ConfigDict(extra="forbid")

    recommendation_id: StrictStr
    patient_id: StrictStr
    command: Literal["BookAppointment", "SendToER"]
    explanation: StrictStr
    doctor_id: StrictStr | None = None
    room_id: StrictStr | None = None
    time_slot: StrictStr | None = None
    status: RecommendationStatus = "pending"
    source: Literal["clinician", "system"] = "clinician"


class AuditLogEntry(BaseModel):
    """One audit-trail event."""

    model_config = ConfigDict(extra="forbid")

    event_id: StrictStr
    step_count: StrictInt = Field(..., ge=0)
    actor: AuditActor
    action_type: StrictStr
    patient_id: StrictStr | None = None
    detail: StrictStr
    explanation: StrictStr
    outcome: StrictStr
    average_wait_minutes: StrictInt = Field(default=0, ge=0)


class CapacitySnapshot(BaseModel):
    """Current operational pressure indicators."""

    model_config = ConfigDict(extra="forbid")

    waiting_room_patients: StrictInt = Field(default=0, ge=0)
    average_wait_minutes: StrictInt = Field(default=0, ge=0)
    er_beds_available: StrictInt = Field(default=0, ge=0)
    clinic_rooms_available: StrictInt = Field(default=0, ge=0)
    pressure_level: CapacityPressure = "low"


class PatientObservation(BaseModel):
    """Observable patient information."""

    model_config = ConfigDict(extra="forbid")

    patient_id: StrictStr
    name: StrictStr
    age: StrictInt = Field(..., ge=0)
    symptoms: list[StrictStr] = Field(default_factory=list)
    acuity: PatientAcuity
    required_specialty: StrictStr
    disposition: PatientDisposition = "waiting"
    notes: list[StrictStr] = Field(default_factory=list)
    existing_appointment: AppointmentDetails | None = None
    estimated_wait_minutes: StrictInt = Field(default=0, ge=0)
    uncertainty_level: UncertaintyLevel = "low"
    requires_clinician_review: StrictBool = Field(default=False)


class DoctorScheduleObservation(BaseModel):
    """Observable doctor schedule information."""

    model_config = ConfigDict(extra="forbid")

    doctor_id: StrictStr
    name: StrictStr
    specialty: StrictStr
    status: DoctorStatus = "available"
    available_slots: list[StrictStr] = Field(default_factory=list)


class RoomAvailabilityObservation(BaseModel):
    """Observable room availability information."""

    model_config = ConfigDict(extra="forbid")

    room_id: StrictStr
    room_type: RoomType
    available_slots: list[StrictStr] = Field(default_factory=list)


class HospitalTriageAction(Action):
    """Action model for scheduling, ER escalation, and review workflows."""

    command: ActionCommand = Field(..., description="High level control command.")
    patient_id: StrictStr | None = Field(default=None, description="Target patient.")
    doctor_id: StrictStr | None = Field(default=None, description="Doctor for booking.")
    room_id: StrictStr | None = Field(default=None, description="Room for booking.")
    time_slot: StrictStr | None = Field(default=None, description="Requested time slot.")
    question: StrictStr | None = Field(
        default=None,
        description="Clarifying question or escalation rationale.",
    )
    recommendation_id: StrictStr | None = Field(
        default=None,
        description="Identifier of the pending recommendation to confirm.",
    )

    @model_validator(mode="after")
    def validate_command_arguments(self) -> "HospitalTriageAction":
        if self.command == "BookAppointment":
            required = {
                "patient_id": self.patient_id,
                "doctor_id": self.doctor_id,
                "room_id": self.room_id,
                "time_slot": self.time_slot,
            }
            missing = [name for name, value in required.items() if value is None]
            if missing:
                raise ValueError(f"BookAppointment requires: {', '.join(missing)}")
        elif self.command == "SendToER":
            if self.patient_id is None:
                raise ValueError("SendToER requires patient_id")
        elif self.command in {"RequestMoreInfo", "EscalateToClinician"}:
            if self.patient_id is None or self.question is None:
                raise ValueError(f"{self.command} requires patient_id and question")
        elif self.command == "ConfirmRecommendation":
            if self.recommendation_id is None:
                raise ValueError("ConfirmRecommendation requires recommendation_id")
        return self


class HospitalTriageObservation(Observation):
    """Full observation emitted by the hospital triage benchmark."""

    benchmark: StrictStr = Field(default="hospital_triage")
    task_name: TaskName
    instruction: StrictStr
    message: StrictStr = Field(default="")
    patients: list[PatientObservation] = Field(default_factory=list)
    doctors: list[DoctorScheduleObservation] = Field(default_factory=list)
    rooms: list[RoomAvailabilityObservation] = Field(default_factory=list)
    scheduled_appointments: list[AppointmentDetails] = Field(default_factory=list)
    er_patient_ids: list[StrictStr] = Field(default_factory=list)
    pending_patient_ids: list[StrictStr] = Field(default_factory=list)
    pending_recommendations: list[PendingRecommendation] = Field(default_factory=list)
    capacity: CapacitySnapshot = Field(default_factory=CapacitySnapshot)
    audit_log: list[AuditLogEntry] = Field(default_factory=list)
    available_commands: list[ActionCommand] = Field(
        default_factory=lambda: [
            "BookAppointment",
            "SendToER",
            "RequestMoreInfo",
            "EscalateToClinician",
            "ConfirmRecommendation",
        ]
    )
    reward_breakdown: RewardBreakdown = Field(default_factory=RewardBreakdown)


class HospitalTriageState(State):
    """Internal state exposed for debugging and deterministic evaluation."""

    benchmark: StrictStr = Field(default="hospital_triage")
    task_name: TaskName = Field(default="task_1_routine_checkup")
    current_score: float = Field(default=0.0, ge=0.0, le=1.0)
    max_steps: StrictInt = Field(default=4, ge=1)
    dangerous_outcome: StrictBool = Field(default=False)
    last_action_summary: StrictStr = Field(default="")
    last_info_response: StrictStr = Field(default="")
    last_action_error: StrictStr | None = Field(default=None)
    scheduled_appointments: list[AppointmentDetails] = Field(default_factory=list)
    er_patient_ids: list[StrictStr] = Field(default_factory=list)
    pending_patient_ids: list[StrictStr] = Field(default_factory=list)
    pending_recommendations: list[PendingRecommendation] = Field(default_factory=list)
    audit_log: list[AuditLogEntry] = Field(default_factory=list)
    clinician_reviewed_patient_ids: list[StrictStr] = Field(default_factory=list)
    confirmed_recommendation_ids: list[StrictStr] = Field(default_factory=list)
    action_history: list[StrictStr] = Field(default_factory=list)
    resolution_steps: dict[str, int] = Field(default_factory=dict)
    total_wait_minutes_elapsed: StrictInt = Field(default=0, ge=0)
    capacity: CapacitySnapshot = Field(default_factory=CapacitySnapshot)
